### ISSUE TITLE
Implement the project status system

### ISSUE THREAD

**Issue by vibby** [AdventistCommons/adventistcommons.org#151]
use https://symfony.com/doc/current/workflow.html

**Comment by vibby** [comment]
I added two things, to both product and project :
- an «enabled» flag on product and projects. So a product or a project can be published or unpublished. Which means only admin can see them. Product are unpublished by default, projects are published by default.
- a status about translation : draft (for product only) / ready to translate / translation started / translation completed / proofreading completed / review completed / outdated

**Comment by m-dotcom** [comment]
Great job Vincent. Very well done. 

I see that the project status on some products now says "translatable". Do you think we can name it "Translation in Progress" or "In Translation" or so to make it clearer?

**Comment by vibby** [comment]
Sure, I gave good name in french, maybe not in english :) give me the wording for all please ! You can also make a proposal yourself, The wording is in that file : https://github.com/AdventistCommons/adventistcommons.org/blob/develop/translations/messages.en.yml, you can propose a merge request for new wording by editing the file directly in Github

The status look like that :
```
product:
  status:
    draft: Draft
    Translatable: Translatable
    outdated: Outdated
project:
  status:
    translatable: Translatable
    started: Started
    translated: Translated
    approved: Approved
    reviewed: Reviewed
```

In addition, it would be great to use the adventist commons interface for content in another format than idml. For example, this yml file. So users could participate to translate the adventist commons interface !
